### ISSUE TITLE
def01

### ISSUE THREAD

**Issue by maxdiland** [maxdiland/MultithreadArchiver#3]
When pass parameters:
`c d:/1.txt 1.gzip`

Where `d:/1.txt` - is existing file.

Get:
`Exception in thread "main" java.lang.NullPointerException
        at com.gmail.gorpenko.util.FileUtil.fileNotExist(FileUtil.java:10)
        at com.gmail.gorpenko.Main.validateAndGetDestinationFile(Main.java:65)
        at com.gmail.gorpenko.Main.run(Main.java:36)
        at com.gmail.gorpenko.Main.main(Main.java:20)`

**Comment by maxdiland** [comment]
Done with 0eb01f569e12eeeac307fa9c9abc98b68e698ce4
